repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover -s tests -p test_*.py
        language: system
        pass_filenames: false
